spring.application.name=demo
# Postgres
spring.datasource.url=jdbc:postgresql://test-aws.cpfhesow7unp.us-east-1.rds.amazonaws.com:5432/test-aws
spring.datasource.username=postgres
spring.datasource.password=postgres
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jackson.serialization.fail-on-empty-beans=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#AWS
aws.s3.bucket=a21216396-uady-proyecto-aws
aws.region=us-east-1
aws.sns.topic.arn=arn:aws:sns:us-east-1:427930110122:topic-aws-proyecto